### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by MichaelFBA** [ioteratech/bluetera-firmware#1]
Hello your demo link is broken for the IMU data.
https://github.com/ioteratech/bluetera-firmware/blob/master

Just wondering if you have any kind of calibration for the IMU in your SDK? I would require accurate IMU data with very little drift. With at least some way of correcting drift.

Thanks

**Comment by UnTraDe** [comment]
Hi,

Thanks for the heads up about the link!

Currently we are calibrating the gyro at first startup to minimize the
drift as much as possible, but there will always be some gyro drift.
However, we do implement sensor fusion on-board, which can incorporate the
accelerometer (6-axis fusion) to compensate for the gyro drift on the roll
and pitch axes, and compass (9-axis fusion) for the yaw axis drift. So with
a calibrated compass, theoretically, you should have almost zero drift, as
long as there are no local magnetic interference.
